powertab <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = c("?"))
Sys.setlocale("LC_TIME", "C")
powertab$Time <- paste(powertab$Date, powertab$Time)
powertab$Time <- strptime(powertab$Time, "%d/%m/%Y %H:%M:%S")
powertab$Date <- as.Date(powertab$Date, "%d/%m/%Y")
newdata <- powertab[powertab$Date==as.Date("2007-02-01")|powertab$Date==as.Date("2007-02-02"), ]
attach(newdata)
plot(Time, Global_active_power, col="white", xlab="", ylab="Global Active Power (kilowatts)")
lines(Time, Global_active_power)
plot(Time, Voltage, col="white", xlab="datetime", ylab="Voltage")
lines(Time, Voltage)
plot(Time, Sub_metering_1, col="white", xlab="", ylab="Energy sub meltering")
lines(Time, Sub_metering_1)
lines(Time, Sub_metering_2, col="red")
lines(Time, Sub_metering_3, col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=c(1,1,1),col=c("black","red","blue"), cex=0.7, fill="white", border="white")
plot(Time, Global_reactive_power, col="white", xlab="datetime", ylab="Global_reactive_power")
lines(Time, Global_reactive_power)
dev.copy(png, file="plot4.png", width = 480, height = 480)
dev.off()
detach(newdata)