powertab <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = c("?"))
Sys.setlocale("LC_TIME", "C")
powertab$Time <- paste(powertab$Date, powertab$Time)
powertab$Time <- strptime(powertab$Time, "%d/%m/%Y %H:%M:%S")
powertab$Date <- as.Date(powertab$Date, "%d/%m/%Y")
newdata <- powertab[powertab$Date==as.Date("2007-02-01")|powertab$Date==as.Date("2007-02-02"), ]
attach(newdata)
hist(Global_active_power, col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.copy(png, file="plot1.png", width = 480, height = 480)
dev.off()
detach(newdata)